### PR TITLE
[FEATURE] Runner configuration

### PR DESCRIPTION
**Pull request by StephenKing**
I took over this config from the old runner. Does this represent the best of breed, @stucki @andristeiner @spoonerWeb?

### CODE REVIEW

**Comment by StephenKing** [comment]
@spoonerweb I would need a token for registration.

**Comment by spoonerWeb** [comment]
I can't say anything about this. Please ask Sascha, he's available in Slack. (don't know his GitHub name)

**Comment by stucki** [comment]
Please discuss with @torvitas.

**Comment by spoonerWeb** [comment]
I've sent the token to @StephenKing.

**Pull request merged**
